### ISSUE TITLE
Fix the packagist package or fix documentation

### ISSUE THREAD

**Issue by Bot8** [roadrunner-server/roadrunner-docs#40]
I try to install roadrunner using documentation https://roadrunner.dev/docs/intro-install and find some bug.

When i do installation via **composer**, by running command **composer require spiral/roadrunner**

**composer** downloads **spiral/roadrunner** from **packagist** https://packagist.org/packages/spiral/roadrunner 
which referenced to repo https://github.com/spiral/roadrunner-worker

So i received a light version of roadrunner without **./vendor/bin/rr,** without class **RoadRunner\PSR7Client** and his friends.

By now i fixed it by dirty hack, adding this lines to **composer.json**

```
"repositories": [
      {
            "type": "git",
            "url": "https://github.com/spiral/roadrunner.git"
      }
]
```

Сould you fix the packagist package or fix documentation?

Thanks for attention.

**Comment by bcremer** [comment]
This issue seems to be outdated. 
https://packagist.org/packages/spiral/roadrunner will download  https://github.com/spiral/roadrunner,

Also you need to specify a PSR-7 implementation like ` laminas/laminas-diactoros` or `nyholm/psr7` during download: 

```php
composer require spiral/roadrunner nyholm/psr7
```

```bash
./vendor/bin/rr get-binary
````


```php
<?php

use Spiral\RoadRunner;
use Nyholm\Psr7;

include "vendor/autoload.php";

$worker = RoadRunner\Worker::create();
$psrFactory = new Psr7\Factory\Psr17Factory();

$worker = new RoadRunner\Http\PSR7Worker($worker, $psrFactory, $psrFactory, $psrFactory);

while ($req = $worker->waitRequest()) {
    try {
        $rsp = new Psr7\Response();
        $rsp->getBody()->write('Hello world!');

        $worker->respond($rsp);
    } catch (\Throwable $e) {
        $worker->getWorker()->error((string)$e);
    }
}
```

**Comment by SerafimArts** [comment]
> Also you need to specify a PSR-7 implementation

This is an optional dependency and is only required if PSR is required. Otherwise you can use `HTTPWorker` insetad of `PSRWorker`.
