### ISSUE TITLE
Add docs for roadrunner and nginx proxy / nginx ingress with kubernetes

### ISSUE THREAD

**Issue by litan1106** [roadrunner-server/roadrunner-docs#52]
In real world application, many of us use nginx to handle ssl and cache static assets.

It would be helpful to add docs for them. I found docs on nginx and swoole.

**Comment by rustatian** [comment]
nginx docs done: https://stage-roadrunner.dev.spiral.world/docs/app-server-nginx-with-rr/2023.x/en
